from gpiozero import  Button, TrafficLights, Buzzer
from time import sleep

lights = TrafficLights(25, 8, 7)
button = Button(21)
buzzer = Buzzer(15)
while True:
    button.wait_for_press()
    lights.green.on()
    sleep(2)
    lights.amber.on()
    sleep(2)
    lights.red.on()
    sleep(5)
    lights.off()
    buzzer.on()
    sleep(1)
    buzzer.off()
    sleep(1)
    buzzer.on()
    sleep(2)
    buzzer.off()
    sleep(1)
    buzzer.on()
    sleep(1)
    buzzer.off()
    sleep(1)
    buzzer.on()
    sleep(2)
    buzzer.off()
    sleep(1)
    buzzer.on()
    sleep(10)
    buzzer.off()
GPIO.output(25,8,7,15, GPIO.LOW)